resources:
  - name: angular-bootcamp-repo
    type: git
    source:
      uri: https://github.com/xtreme-david-joo/angular-bootcamp.git
      branch: master

  - name: pws-labs-playground
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: ((pws_email))
      password: ((pws_password))
      organization: ((pws_org))
      space: ((pws_space))
      skip_cert_check: true

jobs:
- name: ui-unit-tests
  plan:
  - get: angular-bootcamp-repo
    trigger: true
  - task: run build
    timeout: 59m
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: djoo/angular-bootcamp
      inputs:
        - name: angular-bootcamp-repo
      run:
        path: bash
        args:
          - "-c"
          - "cd ./angular-bootcamp-repo && sh ./scripts/unit-test.sh"

- name: api-unit-tests
  plan:
  - get: angular-bootcamp-repo
    trigger: true
  - task: run build
    timeout: 59m
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: djoo/angular-bootcamp
      inputs:
        - name: angular-bootcamp-repo
      run:
        path: bash
        args:
          - "-c"
          - "cd ./angular-bootcamp-repo && ./gradlew test"

- name: acceptance-tests
  plan:
  - get: angular-bootcamp-repo
    trigger: true
  - task: run build
    timeout: 59m
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: djoo/angular-bootcamp
      inputs:
        - name: angular-bootcamp-repo
      run:
        path: bash
        args:
          - "-c"
          - "cd ./angular-bootcamp-repo && sh ./scripts/acceptance-test.sh"

- name: deploy
  serial: true
  plan:
  - get: angular-bootcamp-repo
    trigger: true
    passed: [ui-unit-tests, api-unit-tests, acceptance-tests]
  - task: run build
    timeout: 59m
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: djoo/angular-bootcamp
      inputs:
        - name: angular-bootcamp-repo
      outputs:
        - name: output
      run:
        path: bash
        args:
          - "-c"
          - "sh ./angular-bootcamp-repo/scripts/build-ci.sh"
  - put: pws-labs-playground
    params:
      manifest: ./angular-bootcamp-repo/manifest.yml