groups:
- name: Main
  jobs:
  - ui-unit-tests
  - api-unit-tests
  - acceptance-tests
  - deploy
- name: DockerHub
  jobs:
  - update-docker-image

resources:
  - name: angular-bootcamp-repo
    type: git
    source:
      uri: https://github.com/xtreme-david-joo/angular-bootcamp.git
      branch: master

  - name: pws-labs-playground
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: ((pws_username))
      password: ((pws_password))
      organization: ((pws_org))
      space: ((pws_space))
      skip_cert_check: true

  - name: docker-hub
    type: docker-image
    source:
      repository: djoo/angular-spring
      username: ((dh_username))
      password: ((dh_password))

jobs:
- name: update-docker-image
  plan:
  - get: angular-bootcamp-repo
  - put: docker-hub
    params: {build: angular-bootcamp-repo/ci}
    get_params: {rootfs: true}

- name: ui-unit-tests
  plan:
  - get: angular-bootcamp-repo
    trigger: true
  - task: Run UI Unit Tests
    timeout: 59m
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: djoo/angular-spring
      inputs:
        - name: angular-bootcamp-repo
      run:
        path: bash
        args:
          - "-c"
          - "cd ./angular-bootcamp-repo && sh ./scripts/unit-test.sh"

- name: api-unit-tests
  plan:
  - get: angular-bootcamp-repo
    trigger: true
  - task: Run API Unit Tests
    timeout: 59m
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: djoo/angular-spring
      inputs:
        - name: angular-bootcamp-repo
      run:
        path: bash
        args:
          - "-c"
          - "cd ./angular-bootcamp-repo && SPRING_PROFILES_ACTIVE=test ./gradlew test"

- name: acceptance-tests
  plan:
  - get: angular-bootcamp-repo
    trigger: true
  - task: Run Acceptance Tests
    timeout: 59m
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: djoo/angular-spring
      inputs:
        - name: angular-bootcamp-repo
      run:
        path: bash
        args:
          - "-c"
          - "cd ./angular-bootcamp-repo && sh ./scripts/acceptance-test.sh"

- name: deploy
  serial: true
  plan:
  - get: angular-bootcamp-repo
    trigger: true
    passed: [ui-unit-tests, api-unit-tests, acceptance-tests]
  - task: Build
    timeout: 59m
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: djoo/angular-spring
      inputs:
        - name: angular-bootcamp-repo
      outputs:
        - name: output
      run:
        path: bash
        args:
          - "-c"
          - "sh ./angular-bootcamp-repo/scripts/build-ci.sh"
  - put: pws-labs-playground
    params:
      manifest: ./angular-bootcamp-repo/manifest-ci.yml
      current_app_name: [ angular-bootcamp-api, angular-bootcamp-ui ]